networks:
  simplilearn-phpinfo-network:
    internal: true

secrets:
  simplilearn-phpinfo-secret:
    file: ./src/index.php
    
services:
  simplilearn-phpinfo-service:
    command: 
      - -f
      - index.php
      - -S
      - 0.0.0.0:8080
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == worker
      replicas: 2
      resources:
        limits:
          cpus: "0.050"
          memory: 12M
        reservations:
          cpus: "0.050"
          memory: 12M
    entrypoint: /usr/bin/php
    environment:
      HELLO: world
      AUTHOR: Sebastian
    expose:
      - 8080
    image: academiaonline/simplilearn-phpinfo:single-line
    networks:
      - simplilearn-phpinfo-network
    ports:
      - 80:8080
    read_only: true
    secrets:
      -
        gid: '65534'
        mode: 0400
        source: simplilearn-phpinfo-secret
        target: /app/index.php
        uid: '65534'
    user: '65534:65534'
    working_dir: /app/
  
version: '3.8'
