apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: phpinfo-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      phpinfo: "true"
  template:
    metadata:
      labels:
        phpinfo: "true"
    spec:
      containers:
        -
          image: academiaonline/simplilearn-phpinfo:latest
          name: phpinfo-container
