apiVersion: v1
kind: ReplicationController
metadata:
  name: simplilearn-phpinfo-rc
spec:
  replicas: 2
  selector:
    simplilearn-phpinfo-key: simplilearn-phpinfo-value
  template:
    metadata:
      labels:
        simplilearn-phpinfo-key: simplilearn-phpinfo-value
    spec:
      containers:
        -
          args:
            - -f
            - index.php
            - -S
            - 0.0.0.0:8080
          command:
            - /usr/bin/php
          env:
            - 
              name: HELLO
              value: world
            - 
              name: AUTHOR
              value: Sebastian
          image: academiaonline/simplilearn-phpinfo:single-line
          name: simplilearn-phpinfo-container
          ports:
            - 
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 10m
              memory: 100M
            requests:
              cpu: 10m
              memory: 20M
          volumeMounts:
            -
              mountPath: /app/index.php
              name: simplilearn-phpinfo-volume
              readOnly: true
              subPath: index.php
          workingDir: /app/
      volumes:
        -
          name: simplilearn-phpinfo-volume
          secret:
            secretName: simplilearn-phpinfo-secret
          
    
    
