apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simplilearn-phpinfo-rs-secret
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simplilearn-phpinfo-rs-secret
  template:
    metadata:
      labels:
        app: simplilearn-phpinfo-rs-secret
    spec:
      containers:
        -
          args:
            - -f
            - index.php
            - -S
            - 0.0.0.0:8080
          command:
            - /usr/bin/php
          env:
            - 
              name: OWNER
              value: Sebastian
          image: academiaonline/simplilearn-phpinfo:1.1
          name: simplilearn-phpinfo-container
          volumeMounts:
            -
              mountPath: /src/index.php
              name: src
              readOnly: true
              subPath: index.php
          workingDir: /src/
      volumes:
        - 
          name: src
          secret:
            defaultMode: 0400
            secretName: src
          
